# Setup

In [1]:
import pandas as pd
import numpy as np
import re
import os
import warnings
warnings.filterwarnings('ignore')

# Data Generate

### Encode

In [2]:
df = pd.read_csv("../Data/train_label.csv")

# 声明比特位矩阵,初始化序列号
c = df.values
new = np.zeros([c.shape[0],7])
new[:,0] = c[:,0]

for i in range(c.shape[0]):
    new[i,1:] = sum(map(lambda x:np.eye(6)[int(x)-1], re.findall("\d", c[i,1])))

In [3]:
np.savetxt('../Data/processed_label.csv',new,delimiter=',')

### Refine

In [5]:
# 有效非空属性
selected_features = np.array([\
       0,  1,  2,  3,  4,  5,  6, \
       11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, \
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

# 时序样本路径
PATH = os.path.join('..','Data','train')

sample = pd.read_csv(PATH +'/'+ '0.csv')
newdata = sample.iloc[:,selected_features+1]
sample0 = newdata.dropna().describe().iloc[[1],:]

for i in range(2983):
    data = pd.read_csv(PATH +'/'+ str(i+1)+'.csv')
    newdata = data.iloc[:,selected_features+1]
    sample0 = sample0.append(newdata.dropna().describe().iloc[[1],:],ignore_index=True)

label= pd.read_csv("../Data/processed_label.csv",header=None)

# "零label"的样本量计量列表
counts=[]
for i in range(2983):
    if i not in label.values[:,0]:
        counts.append(i)

label0 = pd.concat([pd.DataFrame([[i,0,0,0,0,0,0]]) for i in counts])
label=pd.concat([label0,label])
label=label.sort_values([0]).reset_index(drop=True)

### Combine

In [9]:
# # 按列合并
aiops_data = pd.concat([sample0,label.iloc[:,1:]],axis=1)

FIN_PATH = os.path.join('..','Data','aiops_data.csv')
aiops_data.to_csv(FIN_PATH,index=False)

# 检验
pd.read_csv(FIN_PATH)

,feature0,feature1,feature2,feature3_1,feature3_2,feature3_3,feature3_4,feature11,feature12,feature13,...,feature69_3,feature69_4,feature69_5,feature69_6,1,2,3,4,5,6
0,1092.520800,24.730000,3.952400,20.880000,0.000000,0.000000,1368.440000,0.015200,5.228400,340252.320000,...,4.593200,6.601200,1.710800,6.708400,0.0,0.0,0.0,0.0,0.0,0.0
1,684.389444,18.527222,3.968333,12.333333,0.000000,0.000000,1290.888889,0.005000,8.860000,325444.444444,...,2.163333,0.475556,-0.339444,3.132778,0.0,0.0,0.0,0.0,0.0,0.0
2,369.106667,12.888889,3.447778,73.666667,0.000000,479.333333,794.222222,0.146667,11.042222,331398.333333,...,-4.681111,-8.103333,-4.478889,-6.862222,0.0,0.0,0.0,0.0,0.0,0.0
3,261.204286,15.137143,2.047143,32.500000,1184.928571,93.642857,0.000000,0.907143,11.715000,320818.142857,...,-7.741429,-8.435000,-4.255000,-12.586429,0.0,0.0,0.0,0.0,0.0,0.0
4,603.202500,25.222500,2.010833,32.083333,1310.083333,45.750000,0.000000,0.012500,5.756667,339515.250000,...,12.569167,9.187500,13.438333,3.495833,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,263.856667,13.133333,2.343333,37.666667,1253.333333,0.000000,294.333333,0.073333,12.533333,391001.333333,...,-12.976667,-14.166667,-12.793333,-15.250000,0.0,0.0,1.0,0.0,0.0,0.0
2980,284.380000,15.090000,2.930000,53.000000,0.000000,1514.000000,0.000000,0.000000,6.730000,377350.000000,...,-18.560000,5.250000,3.000000,-8.380000,0.0,0.0,1.0,0.0,0.0,0.0
2981,215.077500,14.237500,2.970000,24.000000,0.000000,1573.000000,0.000000,0.000000,8.700000,338963.750000,...,-2.532500,-11.002500,-11.780000,-13.767500,0.0,0.0,1.0,0.0,0.0,0.0
2982,247.040000,13.620000,1.980000,33.000000,1568.000000,0.000000,0.000000,0.000000,9.430000,334564.000000,...,-5.130000,-1.310000,3.810000,0.630000,0.0,0.0,1.0,0.0,0.0,0.0
2983,163.515000,16.785000,1.060000,1502.000000,93.000000,0.000000,0.000000,0.000000,10.315000,332645.500000,...,-4.470000,-6.785000,4.970000,-1.910000,0.0,0.0,1.0,0.0,0.0,0.0